version: '3.7'

services:
  web:
    build:
      context: ./unammedAPI

    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./unammedAPI/:/usr/src/unammedAPI/
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=fooBanned
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=hello_django_dev
      - SQL_USER=hello_django
      - SQL_PASSWORD=hello_django
      - SQL_HOST=db
      - SQL_PORT=5432
    depends_on:
      - db
  db:
    image: postgres:11.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django_logger
      - POSTGRES_PASSWORD=django_logger
      - POSTGRES_DB=rest_logger
volumes:
  postgres_data: